name: Test GCC
on:
  workflow_dispatch:

jobs:
  build-windows:
    name: Windows Test
    runs-on: windows-latest
    steps:
    - name: Setup gcc
      run: |
        curl -o gcc.7z -L https://github.com/brechtsanders/winlibs_mingw/releases/download/13.2.0-16.0.6-11.0.0-ucrt-r1/winlibs-x86_64-posix-seh-gcc-13.2.0-mingw-w64ucrt-11.0.0-r1.7z
        7z x gcc.7z
    - name: Display GCC version
      run: |
        mingw64/bin/g++ --version

  build-linux:
    name: Linux Test
    runs-on: ubuntu-latest
    steps:
    - name: Display GCC version
      run: |
        g++ --version
        g++-13 --version
